import {
  AirVent,
  Anchor,
  Award,
  Backpack,
  BadgeCheck,
  Banknote,
  Battery,
  Bed,
  Bell,
  Bike,
  Boxes,
  Box,
  Briefcase,
  Building2,
  BusFront,
  Cable,
  Camera,
  CarFront,
  ChefHat,
  CircleDollarSign,
  CircleParking,
  ClipboardCheck,
  Coffee,
  Compass,
  Container,
  Crown,
  Cylinder,
  Database,
  Dog,
  DoorOpen,
  Dumbbell,
  Eye,
  Fan,
  Fingerprint,
  Flame,
  Flashlight,
  Forklift,
  Fuel,
  Gauge,
  Globe,
  Hammer,
  HardHat,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  IdCard,
  Key,
  Keyboard,
  Lamp,
  Laptop,
  Layers,
  Leaf,
  LifeBuoy,
  Lightbulb,
  Lock,
  LockKeyhole,
  Magnet,
  Mailbox,
  MapPin,
  Megaphone,
  Microwave,
  Milestone,
  Music,
  Newspaper,
  Package,
  PackageOpen,
  PaintRoller,
  ParkingCircle,
  PartyPopper,
  PawPrint,
  PhoneCall,
  Pickaxe,
  Pill,
  PlaneTakeoff,
  Plug,
  Power,
  Printer,
  Radar,
  Radio,
  RefreshCw,
  Refrigerator,
  Repeat,
  Rocket,
  Route,
  Ruler,
  Scale,
  ScanLine,
  Server,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShowerHead,
  Siren,
  Snowflake,
  Sofa,
  Sparkles,
  Speaker,
  SquareParking,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Target,
  ThermometerSun,
  Timer,
  Toilet,
  Trash2,
  TreePine,
  TriangleAlert,
  Truck,
  Tv,
  Umbrella,
  Usb,
  Utensils,
  Vibrate,
  Video,
  WashingMachine,
  Watch,
  Waves,
  Wifi,
  Wind,
  Wine,
  Workflow,
  Wrench,
  Zap,
  ZapOff,
  type LucideIcon,
} from "lucide-react"

export type AmenityIconEntry = { name: string; icon: LucideIcon; tags: string[] }

export const AMENITY_ICONS: AmenityIconEntry[] = [
  { name: "Coffee", icon: Coffee, tags: ["drink", "cafe", "lounge", "comfort"] },
  { name: "Utensils", icon: Utensils, tags: ["food", "dining", "restaurant", "kitchen"] },
  { name: "ChefHat", icon: ChefHat, tags: ["food", "kitchen", "cooking"] },
  { name: "Microwave", icon: Microwave, tags: ["kitchen", "food", "appliance"] },
  { name: "Refrigerator", icon: Refrigerator, tags: ["fridge", "kitchen", "appliance"] },
  { name: "Wine", icon: Wine, tags: ["drink", "alcohol"] },
  { name: "ShoppingBag", icon: ShoppingBag, tags: ["shop", "retail", "store"] },
  { name: "Bed", icon: Bed, tags: ["sleep", "rest", "bunk", "lodging"] },
  { name: "Sofa", icon: Sofa, tags: ["lounge", "rest", "comfort", "furniture"] },
  { name: "ShowerHead", icon: ShowerHead, tags: ["shower", "bath", "wash"] },
  { name: "Toilet", icon: Toilet, tags: ["restroom", "bathroom"] },
  { name: "WashingMachine", icon: WashingMachine, tags: ["laundry", "wash"] },
  { name: "Tv", icon: Tv, tags: ["television", "entertainment", "lounge"] },
  { name: "Music", icon: Music, tags: ["audio", "entertainment"] },
  { name: "Headphones", icon: Headphones, tags: ["audio", "music"] },
  { name: "Speaker", icon: Speaker, tags: ["audio", "sound"] },
  { name: "Dumbbell", icon: Dumbbell, tags: ["gym", "fitness", "wellness"] },
  { name: "Heart", icon: Heart, tags: ["health", "wellness", "medical"] },
  { name: "Stethoscope", icon: Stethoscope, tags: ["medical", "doctor", "health"] },
  { name: "Pill", icon: Pill, tags: ["medical", "pharmacy", "health"] },
  { name: "LifeBuoy", icon: LifeBuoy, tags: ["safety", "rescue", "emergency"] },

  { name: "ShieldCheck", icon: ShieldCheck, tags: ["security", "protection", "safe"] },
  { name: "ShieldAlert", icon: ShieldAlert, tags: ["security", "warning"] },
  { name: "Lock", icon: Lock, tags: ["security", "secure"] },
  { name: "LockKeyhole", icon: LockKeyhole, tags: ["security", "lock"] },
  { name: "Key", icon: Key, tags: ["security", "access"] },
  { name: "IdCard", icon: IdCard, tags: ["badge", "id", "credential"] },
  { name: "Fingerprint", icon: Fingerprint, tags: ["biometric", "security"] },
  { name: "BadgeCheck", icon: BadgeCheck, tags: ["verified", "security"] },
  { name: "Camera", icon: Camera, tags: ["surveillance", "security", "cctv"] },
  { name: "Video", icon: Video, tags: ["camera", "surveillance"] },
  { name: "Eye", icon: Eye, tags: ["watch", "surveillance"] },
  { name: "Siren", icon: Siren, tags: ["alarm", "emergency", "security"] },
  { name: "DoorOpen", icon: DoorOpen, tags: ["entrance", "access"] },
  { name: "Bell", icon: Bell, tags: ["alert", "notification"] },
  { name: "PhoneCall", icon: PhoneCall, tags: ["contact", "call"] },
  { name: "Megaphone", icon: Megaphone, tags: ["broadcast", "alert"] },

  { name: "Truck", icon: Truck, tags: ["vehicle", "transport", "logistics"] },
  { name: "Forklift", icon: Forklift, tags: ["cargo", "warehouse", "lift"] },
  { name: "Container", icon: Container, tags: ["cargo", "shipping"] },
  { name: "Box", icon: Box, tags: ["package", "cargo"] },
  { name: "Boxes", icon: Boxes, tags: ["cargo", "warehouse", "stack"] },
  { name: "Package", icon: Package, tags: ["cargo", "shipping"] },
  { name: "PackageOpen", icon: PackageOpen, tags: ["cargo", "unpack"] },
  { name: "Scale", icon: Scale, tags: ["weight", "weigh", "measurement"] },
  { name: "Ruler", icon: Ruler, tags: ["measure", "size"] },
  { name: "ScanLine", icon: ScanLine, tags: ["barcode", "scan"] },
  { name: "Snowflake", icon: Snowflake, tags: ["cold", "reefer", "refrigerated", "freeze"] },
  { name: "ThermometerSun", icon: ThermometerSun, tags: ["temperature", "heat"] },
  { name: "Flame", icon: Flame, tags: ["fire", "hazmat"] },
  { name: "TriangleAlert", icon: TriangleAlert, tags: ["warning", "hazmat", "danger"] },
  { name: "Cylinder", icon: Cylinder, tags: ["tank", "fuel", "gas"] },

  { name: "SquareParking", icon: SquareParking, tags: ["parking", "park"] },
  { name: "ParkingCircle", icon: ParkingCircle, tags: ["parking"] },
  { name: "CircleParking", icon: CircleParking, tags: ["parking"] },
  { name: "CarFront", icon: CarFront, tags: ["vehicle", "car", "parking"] },
  { name: "BusFront", icon: BusFront, tags: ["bus", "transit"] },
  { name: "Bike", icon: Bike, tags: ["bicycle", "transit"] },
  { name: "Ship", icon: Ship, tags: ["boat", "marine", "port"] },
  { name: "Anchor", icon: Anchor, tags: ["port", "marine"] },
  { name: "PlaneTakeoff", icon: PlaneTakeoff, tags: ["air", "transit"] },
  { name: "Route", icon: Route, tags: ["path", "navigation"] },
  { name: "MapPin", icon: MapPin, tags: ["location", "map"] },
  { name: "Compass", icon: Compass, tags: ["navigation", "direction"] },
  { name: "Globe", icon: Globe, tags: ["world", "global"] },
  { name: "Milestone", icon: Milestone, tags: ["distance", "marker"] },

  { name: "Wifi", icon: Wifi, tags: ["internet", "network", "connectivity"] },
  { name: "Plug", icon: Plug, tags: ["power", "outlet", "electric"] },
  { name: "Power", icon: Power, tags: ["electric", "energy"] },
  { name: "Zap", icon: Zap, tags: ["power", "ev", "electric", "fast"] },
  { name: "ZapOff", icon: ZapOff, tags: ["power", "off"] },
  { name: "Battery", icon: Battery, tags: ["power", "ev", "charge"] },
  { name: "Cable", icon: Cable, tags: ["wire", "power"] },
  { name: "Lightbulb", icon: Lightbulb, tags: ["light", "idea"] },
  { name: "Lamp", icon: Lamp, tags: ["light"] },
  { name: "Flashlight", icon: Flashlight, tags: ["light", "torch"] },
  { name: "Sun", icon: Sun, tags: ["solar", "outdoor"] },
  { name: "Wind", icon: Wind, tags: ["air", "weather"] },
  { name: "AirVent", icon: AirVent, tags: ["hvac", "air", "ventilation"] },
  { name: "Fan", icon: Fan, tags: ["cooling", "hvac"] },
  { name: "Waves", icon: Waves, tags: ["water"] },
  { name: "Database", icon: Database, tags: ["server", "data"] },
  { name: "Server", icon: Server, tags: ["it", "data"] },
  { name: "Usb", icon: Usb, tags: ["port", "device"] },
  { name: "Keyboard", icon: Keyboard, tags: ["device", "computer"] },
  { name: "Laptop", icon: Laptop, tags: ["computer", "device"] },
  { name: "Printer", icon: Printer, tags: ["office", "device"] },
  { name: "Radio", icon: Radio, tags: ["comms", "broadcast"] },
  { name: "Radar", icon: Radar, tags: ["scan", "tracking"] },

  { name: "Fuel", icon: Fuel, tags: ["gas", "diesel", "fuel"] },
  { name: "Wrench", icon: Wrench, tags: ["repair", "mechanic", "tool"] },
  { name: "Hammer", icon: Hammer, tags: ["repair", "tool", "build"] },
  { name: "Pickaxe", icon: Pickaxe, tags: ["tool", "build"] },
  { name: "PaintRoller", icon: PaintRoller, tags: ["tool", "decor"] },
  { name: "HardHat", icon: HardHat, tags: ["safety", "construction"] },
  { name: "ClipboardCheck", icon: ClipboardCheck, tags: ["inspection", "checklist"] },
  { name: "Settings", icon: Settings, tags: ["config", "tools"] },
  { name: "Workflow", icon: Workflow, tags: ["process", "operations"] },
  { name: "Repeat", icon: Repeat, tags: ["recurring"] },
  { name: "RefreshCw", icon: RefreshCw, tags: ["refresh", "renew"] },
  { name: "Timer", icon: Timer, tags: ["time", "schedule"] },
  { name: "Watch", icon: Watch, tags: ["time", "schedule"] },
  { name: "Sparkles", icon: Sparkles, tags: ["clean", "service", "premium"] },
  { name: "Magnet", icon: Magnet, tags: ["attraction", "metal"] },
  { name: "Vibrate", icon: Vibrate, tags: ["alert", "device"] },
  { name: "Mailbox", icon: Mailbox, tags: ["mail", "post"] },
  { name: "Newspaper", icon: Newspaper, tags: ["news", "media"] },

  { name: "Building2", icon: Building2, tags: ["office", "facility"] },
  { name: "Home", icon: Home, tags: ["building", "house"] },
  { name: "Briefcase", icon: Briefcase, tags: ["business", "work"] },
  { name: "Backpack", icon: Backpack, tags: ["luggage", "bag"] },
  { name: "Star", icon: Star, tags: ["favorite", "rating"] },
  { name: "Crown", icon: Crown, tags: ["premium", "vip"] },
  { name: "Award", icon: Award, tags: ["badge", "premium"] },
  { name: "Gauge", icon: Gauge, tags: ["meter", "speed"] },
  { name: "Banknote", icon: Banknote, tags: ["money", "cash"] },
  { name: "CircleDollarSign", icon: CircleDollarSign, tags: ["money", "payment"] },
  { name: "Tag", icon: Tag, tags: ["label", "tag"] },
  { name: "Layers", icon: Layers, tags: ["stack", "level"] },
  { name: "Target", icon: Target, tags: ["goal", "kpi"] },
  { name: "Rocket", icon: Rocket, tags: ["launch", "fast"] },
  { name: "PartyPopper", icon: PartyPopper, tags: ["event", "celebration"] },
  { name: "Trash2", icon: Trash2, tags: ["waste", "garbage", "disposal"] },
  { name: "TreePine", icon: TreePine, tags: ["outdoor", "nature"] },
  { name: "Leaf", icon: Leaf, tags: ["green", "eco"] },
  { name: "Umbrella", icon: Umbrella, tags: ["weather", "rain"] },
  { name: "PawPrint", icon: PawPrint, tags: ["pet", "animal"] },
  { name: "Dog", icon: Dog, tags: ["pet", "animal"] },
  { name: "HelpCircle", icon: HelpCircle, tags: ["help", "info"] },
]

const ICON_BY_NAME = new Map(AMENITY_ICONS.map((i) => [i.name, i.icon]))

export const iconByName = (name: string): LucideIcon =>
  ICON_BY_NAME.get(name) ?? Tag

export const searchIcons = (query: string): AmenityIconEntry[] => {
  const q = query.trim().toLowerCase()
  if (!q) return AMENITY_ICONS
  return AMENITY_ICONS.filter(({ name, tags }) => {
    if (name.toLowerCase().includes(q)) return true
    return tags.some((t) => t.includes(q))
  })
}
